In [1]:
import os, sys
pathname = os.path.dirname("/home/jgutman/mvesc/Models_Results/")
full_pathname = os.path.abspath(pathname)
split_pathname = full_pathname.split(sep="mvesc")
base_pathname = os.path.join(split_pathname[0], "mvesc")
parentdir = os.path.join(base_pathname, "ETL")
sys.path.insert(0,parentdir)

In [2]:
from mvesc_utility_functions import *

In [130]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.grid_search import ParameterGrid
from sklearn.grid_search import GridSearchCV
from sklearn.cross_validation import *
from sklearn.externals import joblib
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import roc_curve

import yaml
import numpy as np
import pandas as pd

In [3]:
query = """select * from model.outcome"""

In [102]:
with postgres_pgconnection_generator() as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
            results = cursor.fetchall()
            print(len(results))
        connection.commit()

11777


In [6]:
np.random.seed(model_options['randomSeed'])

In [134]:
def build_outcomes_plus_features(model_options):
    with postgres_pgconnection_generator() as connection:
        # get labeled outcomes
        # Assumes:
        # model.outcome table contains a column (name given in cohort_grade_level_begin) for each cohort base year we choose
        # e.g. 'cohort_9th' contains the year each student is seen in 9th grade
        # and contains an outcome column (name given in outcome_name)
        # and 'student_lookup' columns
        # Usage:
        # select train, validation, and test based on values in column
        # 'cohort_grade_level_begin' according to value in 'cohorts_held_out'
        outcomes_with_student_lookup = read_table_to_df(connection,
            table_name = 'outcome', schema = 'model', nrows = -1,
            columns = ['student_lookup', model_options['outcome_name'], model_options['cohort_grade_level_begin']])
        # drop students without student_lookup, outcome, or cohort identifier
        # can use subset = [colnames] to drop based on NAs in certain columns only
        outcomes_with_student_lookup.dropna(inplace=True)
        joint_label_features = outcomes_with_student_lookup.copy()

        # get all requested input features
        # Assumes:
        # every features table contains 'student_lookup'
        # plus a column for the requested possible features

        for table, column_names in model_options['features_included'].items():
            features = read_table_to_df(connection, table_name = table,
                schema = 'model', nrows = -1,
                columns=(['student_lookup'] + column_names))
        # join to only keep features that have labeled outcomes
            joint_label_features = pd.merge(joint_label_features, features,
                how = 'left', on = 'student_lookup')

    # build dataframe containing student_lookup, outcome, cohort,
    # and all features as numeric non-categorical values
    joint_label_features.set_index('student_lookup', inplace=True)
    joint_label_features = df2num(joint_label_features)
    return joint_label_features

In [75]:
def df2num(rawdf):
    """ Convert data frame with numeric variables and strings to numeric dataframe

    :param pd.dataframe rawdf: raw data frame
    :returns pd.dataframe df: a data frame with strings converted to dummies, other columns unchanged
    :rtype: pd.dataframe
    Rules:
    - 1. numeric columns unchanged;
    - 2. strings converted to dummeis;
    - 3. the most frequent string is taken as reference
    - 4. new column name is: "ColumnName_Category"
    (e.g., column 'gender' with 80 'M' and 79 'F'; the dummy column left is 'gender_F')

    """
    numeric_df = rawdf.select_dtypes(include=[np.number])
    str_columns = [col for col in rawdf.columns if col not in numeric_df.columns]
    dummy_col_df = pd.get_dummies(rawdf[str_columns], dummy_na=True)
    numeric_df = numeric_df.join(dummy_col_df)
    most_frequent_values = rawdf[str_columns].mode().loc[0].to_dict()
    reference_cols = ["{}_{}".format(key, value) for key, value in most_frequent_values.items()]
    numeric_df.drop(reference_cols, axis=1, inplace=True)
    return numeric_df

In [93]:
from sklearn.cross_validation import LeaveOneLabelOut

In [97]:
cohort_kfolds = LeaveOneLabelOut(joint_label_features[modelOptions['cohort_grade_level_begin']])
len(cohort_kfolds)

7

In [158]:
def define_clfs_params():
    clfs = {'logit': LogisticRegression(),
    'DT': DecisionTreeClassifier()
    }

    grid = {'logit': {'penalty': ['l1','l2'], 'C': [0.00001,0.0001,0.001,0.01,0.1,1,10]},
        'DT': {'criterion': ['gini', 'entropy'], 'max_depth': [1,5,10,20,50,100], 'max_features': ['sqrt','log2'],'min_samples_split': [2,5,10]}
    }
    return clfs, grid

In [159]:
clfs, params = define_clfs_params()

In [165]:
from sklearn.grid_search import ParameterGrid, GridSearchCV

In [164]:
param_grid = ParameterGrid(params['logit'])

In [170]:
GridSearchCV(clf, params['logit'], scoring=criterion, cv=cohort_kfolds)

GridSearchCV(cv=sklearn.cross_validation.LeaveOneLabelOut(labels=[2006 2006 ..., 2011 2011]),
       error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'penalty': ['l1', 'l2'], 'C': [1e-05, 0.0001, 0.001, 0.01, 0.1, 1, 10]},
       pre_dispatch='2*n_jobs', refit=True, scoring='f1', verbose=0)

In [118]:
with open('model_options.yaml', 'r') as f:
    model_options = yaml.load(f)
assert(type(model_options)==dict)
assert(type(model_options['features_included']))

In [166]:
clf = LogisticRegression()
criterion='f1'

In [167]:
cohort_kfolds

sklearn.cross_validation.LeaveOneLabelOut(labels=[2006 2006 2006 ..., 2011 2011 2011])

In [110]:
model_options['features_included']

[{'demographics': ['ethnicity', 'gender']}, {'grades': ['gpa_8th']}]

In [115]:
type(model_options['features_included'])

dict

In [136]:
outcome_plus_features

not_on_time  cohort_9th  ethnicity_A  ethnicity_B  \
student_lookup                                                      
57296.0                   0        2006          0.0          0.0   
58652.0                   0        2006          0.0          0.0   
57294.0                   0        2006          0.0          0.0   
69065.0                   1        2006          0.0          0.0   
63909.0                   1        2006          0.0          1.0   
57292.0                   0        2006          0.0          0.0   
57290.0                   0        2006          0.0          0.0   
57288.0                   0        2006          0.0          0.0   
57285.0                   0        2006          0.0          0.0   
57284.0                   0        2006          0.0          0.0   
57282.0                   0        2006          0.0          0.0   
41726.0                   1        2006          0.0          0.0   
57279.0                   0        2006          0.0          0.0   
57278.0                   0        2006          0.0          0.0   
57277.0                   0        2006          0.0          0.0   
57276.0                   1        2006          0.0          0.0   
57275.0                   0        2006          0.0          0.0   
57274.0                   0        2006          0.0          0.0   
57273.0                   0        2006          0.0          0.0   
57271.0                   0        2006          0.0          0.0   
57270.0                   0        2006          0.0          0.0   
57268.0                   0        2006          0.0          0.0   
57266.0                   0        2006          0.0          0.0   
57265.0                   0        2006          0.0          0.0   
57264.0                   0        2006          0.0          0.0   
57259.0                   0        2006          0.0          0.0   
58523.0                   0        2006          0.0          0.0   
36739.0                   1        2006          0.0          0.0   
57255.0                   0        2006          0.0          0.0   
57254.0                   0        2006          0.0          0.0   
...                     ...         ...          ...          ...   
70804.0                   1        2012          0.0          0.0   
19548.0                   0        2012          0.0          0.0   
699419.0                  1        2012          0.0          0.0   
19308.0                   1        2012          0.0          0.0   
19154.0                   0        2012          0.0          0.0   
19150.0                   1        2012          0.0          0.0   
19149.0                   1        2012          0.0          0.0   
19123.0                   1        2012          0.0          0.0   
19061.0                   0        2012          0.0          0.0   
19055.0                   0        2012          0.0          0.0   
700797.0                  1        2012          0.0          0.0   
19044.0                   0        2012          0.0          0.0   
19040.0                   0        2012          0.0          0.0   
19039.0                   0        2012          0.0          0.0   
19038.0                   0        2012          0.0          0.0   
19037.0                   1        2012          0.0          0.0   
19036.0                   0        2012          0.0          0.0   
19035.0                   0        2012          0.0          0.0   
19034.0                   0        2012          0.0          0.0   
700539.0                  1        2012          0.0          0.0   
19033.0                   0        2012          0.0          0.0   
700311.0                  1        2012          0.0          0.0   
19032.0                   0        2012          0.0          0.0   
19028.0                   0        2012          0.0          0.0   
19027.0                   0        2012          0.0          0.0   
19026.0       

In [122]:
def temporal_cohort_test_split(joint_df, cohort_grade_level_begin,
    cohorts_held_out):
    """ Splits the given joint_df of features & outcomes and
    returns a train/test dataset
    :param pd.DataFrame joint_df:
    :param list[int] cohorts_held_out:
    """
    train = joint_df[~joint_df[cohort_grade_level_begin].isin(cohorts_held_out)]
    test = joint_df[joint_df[cohort_grade_level_begin].isin(cohorts_held_out)]
    return train, test

In [138]:
train, test = temporal_cohort_test_split(outcome_plus_features,
    model_options['cohort_grade_level_begin'],
    model_options['cohorts_held_out'])

In [128]:
print(pd.unique(train.cohort_9th))
print(pd.unique(test.cohort_9th))

[2006 2007 2008 2009 2010 2011]
[2012]


In [146]:
cohort_kfolds = LeaveOneLabelOut(train[model_options['cohort_grade_level_begin']])

In [148]:
random_kfolds = LabelKFold(train.index, n_folds=10)

In [ ]:
def clf_loop(clfs, params, criterion, models_to_run, cv_folds, X_train, X_test, y_train, y_test):
    best_validated_models = dict()
    for index,clf in enumerate([clfs[x] for x in models_to_run]):
        model_name=models_to_run[index]
        print(model_name)
        parameter_values = params[models_to_run[index]]
        param_grid = ParameterGrid(parameter_values)
        best_validated_models[model_name] = GridSearchCV(clf, param_grid, scoring=criterion, cv=cv_folds)
        model_cv_score = best_validated_models[model_name].best_score_
        print("model: {model} score: {score}".format(model=model_name), score=model_cv_score)
    return best_validated_models

In [151]:
    # get subtables for each for easy reference
    train_X = train.drop([model_options['outcome_name'],
        model_options['cohort_grade_level_begin']],axis=1)
    test_X = test.drop([model_options['outcome_name'],
        model_options['cohort_grade_level_begin']],axis=1)
    train_y = train[model_options['outcome_name']]
    test_y = test[model_options['outcome_name']]

In [153]:
train_y

student_lookup
57296.0     0
58652.0     0
57294.0     0
69065.0     1
63909.0     1
57292.0     0
57290.0     0
57288.0     0
57285.0     0
57284.0     0
57282.0     0
41726.0     1
57279.0     0
57278.0     0
57277.0     0
57276.0     1
57275.0     0
57274.0     0
57273.0     0
57271.0     0
57270.0     0
57268.0     0
57266.0     0
57265.0     0
57264.0     0
57259.0     0
58523.0     0
36739.0     1
57255.0     0
57254.0     0
           ..
701016.0    1
701036.0    1
701037.0    1
701041.0    1
701046.0    1
701056.0    1
701058.0    1
701067.0    1
701084.0    1
701090.0    1
701091.0    1
701093.0    1
701097.0    1
701098.0    1
701099.0    1
701100.0    1
701101.0    1
701105.0    1
701108.0    1
701110.0    1
701115.0    1
701121.0    1
701130.0    1
701139.0    1
701145.0    1
701148.0    1
701157.0    1
701163.0    1
701165.0    1
701168.0    1
Name: not_on_time, dtype: int64

In [154]:
dict()==dict()

True

In [155]:
if dict():
    print('yes')

In [156]:
filename=os.path.join(base_pathname, 
    'Models_Results', 'model_options.yaml')

In [157]:
filename

'/home/jgutman/mvesc/Models_Results/model_options.yaml'

In [171]:
from estimate_prediction_model import *

FileNotFoundError: [Errno 2] No such file or directory: '/home/jgutman/env/lib/python3.4/site-packages/ipykernel/mvesc/Models_Results/model_options.yaml'

In [174]:
model_options = read_in_yaml('model_options.yaml')

In [175]:
    # set seed for this program from model_options
    np.random.seed(model_options['random_seed'])

    # Based on options, draw in data and select the appropriate
    # labeled outcome column (outcome_name)
    # cohort identification column (cohort_grade_level_begin)
    # subset of various feature columns from various tables (features_included)

    outcome_plus_features = build_outcomes_plus_features(model_options)

    # Use the gathered DataFrame in a predictive model
    # Steps:
    #   - (A) manage test and validation folds
    #   - (B) run the prediction technique across all validation folds
    #   - (C) record the inputs and parameters used

    # (4A) Choose cohort(s) for test and validation data
    # Validation Process
    # Use temporal split for creating the test set
    # Use cohort-fold cross-validation for parameter search and model selection
    #    - temporal (using recent cohorts as a validation set)
    #    - k-fold cross (using all cohorts and all years of features)
    #    - cohort-fold cross validation (leave one cohort out)

    if model_options['model_test_holdout'] == 'temporal_cohort':
        # if using temporal cohort model performance validation,
        # we choose the cohorts in cohorts_held_out for the test set
        train, test = temporal_cohort_test_split(outcome_plus_features,
            model_options['cohort_grade_level_begin'],
            model_options['cohorts_held_out'])

    else:
        # if not using temporal test set, split randomly
        train, test = train_test_split(outcome_plus_features, test_size=0.20,
            random_state=model_options['random_seed'])

    # get subtables for each for easy reference
    train_X = train.drop([model_options['outcome_name'],
        model_options['cohort_grade_level_begin']],axis=1)
    test_X = test.drop([model_options['outcome_name'],
        model_options['cohort_grade_level_begin']],axis=1)
    train_y = train[model_options['outcome_name']]
    test_y = test[model_options['outcome_name']]

    ####
    # From now on, we IGNORE the `test`, `test_X`, `test_y` data until we evaluate the model
    ####

    ## (4B) Fit on Training ##
    # if we require cross-validation of parameters, we can either
    #    (a) hold out another cohort in each fold for cross-validation
    #    (b) fold all cohorts together for k-fold parameter estimation
    clfs, params = define_clfs_params()

    if model_options['parameter_cross_validation_scheme'] == 'none':
        # no need to further manipulate train dataset
        cohort_kfolds = 2 # hacky way to have GridSearchCV fit to 2 k-folds

    elif model_options['parameter_cross_validation_scheme'] == 'leave_cohort_out':
        # choose another validation set amongst the training set to
        # estimate parameters and model selection across cohort folds
        print('leave_cohort_out')
        cohort_kfolds = LeaveOneLabelOut(train[
                model_options['cohort_grade_level_begin']])

    elif model_options['parameter_cross_validation_scheme'] == 'k_fold':
        # ignore cohorts and use random folds to estimate parameter
        print('k_fold_parameter_estimation')
        cohort_kfolds = LabelKFold(train.index,
            n_folds=model_options[n_folds])

    else:
        print('unknown cross-validation strategy')

    # best_validated_models is a dictionary whose keys are the model
    # nicknames in model_classes_selected and values are objects
    # returned by GridSearchCV
    best_validated_models = clf_loop(clfs, params, train_X, train_y,
        criterion=model_options['validation_criterion'],
        models_to_run=model_options['model_classes_selected'],
        cv_folds=cohort_kfolds)

    for model_name, model in best_validated_models.items():
        print(model_name)
        clf = model.best_estimator_
        if hasattr(clf, "decision_function"):
            test_set_scores = clf.decision_function(test_X)
        else:
            test_set_scores = clf.predict_proba(test_X)

        ## (4C) Save Results ##
        # Save the recorded inputs, model, performance, and text description
        #    into a results folder
        #        according to sklearn documentation, use joblib instead of pickle
        #            save as a .pkl extension
        #        store option inputs (randomSeed, train/test split rules, features)
        #        store time to completion [missing]

        saved_outputs = {
            'estimator' : model,
            'model_options' : model_options, # this also contains cohort_grade_level_begin for train/test split
            'test_y' : test_y,
            'test_set_soft_preds' : test_set_scores,
            'performance_objects' : measure_performance(test_y, test_set_scores)
        }

leave_cohort_out
logit
model: logit score: 0.623774374793434
logit


In [187]:
test_set_scores = best_validated_models['logit'].predict_proba(test_X)

In [193]:
measure_performance(test_y, test_set_scores[:,1])

{'pr_curve': (array([ 0.24518519,  1.        ]),
  array([ 1.,  0.]),
  array([ 0.5])),
 'roc_curve': (array([ 0.,  1.]), array([ 0.,  1.]), array([ 1.5,  0.5]))}

In [192]:
test_set_scores[:,1].shape

(2700,)

In [194]:
from sklearn.metrics import *

In [195]:
precision, recall, thresholds = precision_recall_curve(test_y, test_set_scores[:,1])

In [196]:
precision

array([ 0.24518519,  1.        ])

In [197]:
thresholds

array([ 0.5])

In [200]:
sum(test_y)/len(test_y)

0.24518518518518517

In [201]:
best_validated_models['logit'].grid_scores_

[mean: 0.62377, std: 0.00527, params: {'penalty': 'l1', 'C': 1e-05},
 mean: 0.34926, std: 0.09790, params: {'penalty': 'l2', 'C': 1e-05},
 mean: 0.62377, std: 0.00527, params: {'penalty': 'l1', 'C': 0.0001},
 mean: 0.34200, std: 0.03333, params: {'penalty': 'l2', 'C': 0.0001},
 mean: 0.62377, std: 0.00527, params: {'penalty': 'l1', 'C': 0.001},
 mean: 0.34299, std: 0.03393, params: {'penalty': 'l2', 'C': 0.001},
 mean: 0.56849, std: 0.09264, params: {'penalty': 'l1', 'C': 0.01},
 mean: 0.35608, std: 0.02978, params: {'penalty': 'l2', 'C': 0.01},
 mean: 0.35751, std: 0.02510, params: {'penalty': 'l1', 'C': 0.1},
 mean: 0.35617, std: 0.02687, params: {'penalty': 'l2', 'C': 0.1},
 mean: 0.35354, std: 0.03216, params: {'penalty': 'l1', 'C': 1},
 mean: 0.35449, std: 0.03231, params: {'penalty': 'l2', 'C': 1},
 mean: 0.34710, std: 0.02758, params: {'penalty': 'l1', 'C': 10},
 mean: 0.34712, std: 0.02759, params: {'penalty': 'l2', 'C': 10}]

In [203]:
sum(best_validated_models['logit'].predict(train_X))

0

In [207]:
clf = LogisticRegression(penalty='l2',C=1e-05)
clf.fit(train_X, train_y)

LogisticRegression(C=1e-05, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [209]:
y_score = clf.predict_proba(train_X)

In [212]:
precision_recall_curve(train_y, y_score[:,1])

(array([ 0.24754875,  0.24638326,  0.24102564,  0.2408359 ,  0.2398761 ,
         0.26097046,  0.26076858,  0.2605113 ,  0.25734024,  0.24614338,
         0.24550216,  0.2412037 ,  0.8       ,  1.        ,  1.        ]),
 array([  1.00000000e+00,   9.85313752e-01,   9.41255007e-01,
          9.38584780e-01,   9.30574099e-01,   5.50511794e-01,
          5.49621718e-01,   5.48731642e-01,   5.30485091e-01,
          4.82866044e-01,   4.79750779e-01,   4.63729417e-01,
          1.78015131e-03,   8.90075656e-04,   0.00000000e+00]),
 array([ 0.49157332,  0.49160378,  0.49161434,  0.49162305,  0.49162498,
         0.49162635,  0.49162882,  0.49437676,  0.49440722,  0.49441779,
         0.4944265 ,  0.49442843,  0.4944298 ,  0.49443227]))

In [214]:
train_y

student_lookup
57296.0     0
58652.0     0
57294.0     0
69065.0     1
63909.0     1
57292.0     0
57290.0     0
57288.0     0
57285.0     0
57284.0     0
57282.0     0
41726.0     1
57279.0     0
57278.0     0
57277.0     0
57276.0     1
57275.0     0
57274.0     0
57273.0     0
57271.0     0
57270.0     0
57268.0     0
57266.0     0
57265.0     0
57264.0     0
57259.0     0
58523.0     0
36739.0     1
57255.0     0
57254.0     0
           ..
701016.0    1
701036.0    1
701037.0    1
701041.0    1
701046.0    1
701056.0    1
701058.0    1
701067.0    1
701084.0    1
701090.0    1
701091.0    1
701093.0    1
701097.0    1
701098.0    1
701099.0    1
701100.0    1
701101.0    1
701105.0    1
701108.0    1
701110.0    1
701115.0    1
701121.0    1
701130.0    1
701139.0    1
701145.0    1
701148.0    1
701157.0    1
701163.0    1
701165.0    1
701168.0    1
Name: not_on_time, dtype: int64